## If enabled, image references use `.Values.registryAlternateRegion` instead of `.Values.registry`.
useAlternateRegion: false

extensions:
  pg_stat_statements:
    max: 1000
    track: all

## Refer to the "ccloud/postgres" repository in Keppel to see which image tags exist.
image: keppel.eu-de-1.cloud.sap/ccloud/postgres
imageTag: "12.15-pgautofailover-2"
pullPolicy: IfNotPresent

node:
  # 2 Replicas for HA failover
  replicas: 2
  podAnnotations: {}
  haproxy: true
monitor:
  podAnnotations: {}

kubernetes_entrypoint_version: v0.3.1

## Create a database user
## Default: postgres
postgresUser: postgres
## Default: random 10 character string
# postgresPassword:

## Create a database
## Default: the postgres user
# postgresDatabase:

# custom db-init.sh
# dbInit: name of a configmap that provides the db-init.sh script

# custom db-maintain.sh
# dbMaintain: name of a configmap that provides the db-maintain.sh script

# Sets the option of the same name in the postgresql.conf. If set to a positive
# integer value, logs statements that run for longer than this many
# milliseconds.
log_min_duration_statement: -1

## Persist data to a persitent volume
persistence:
  enabled: false
  legacy_pvc: true
  accessMode: ReadWriteMany
  size: 10Gi
  # Specificy storageClass
  # storageClass: storageClass
  monitor:
    size: 1Gi
    # Re-use existing (unmanged) PVC
    # existingClaim: claimName

# Size of /dev/shm. If null, we use whatever default amount the container
# runtime gives us (see `df -h /dev/shm` inside the Postgres container).
sharedMemoryLimit: null

probe_timeout_secs: 3
probe_failure_threshold: 6 # number of liveness probes that need to fail to trigger a pod restart

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}

# Default Prometheus alerts and rules.
alerts:
  enabled: true

  # TODO: unused, remove
  prometheus: openstack
  # Name of the Prometheus containing the disk usage metrics.
  prometheus_for_disk_usage: kubernetes

  # The tier label of the alerts.
  tier: os
  # The support group label of the alerts. Must be given in values.yaml of parent chart.
  support_group:

  # Configurable service label of the alerts. Defaults to `.Release.Name`.
  # service:

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: cloud.sap/maintenance-state
              operator: In
              values:
                - operational
