apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-snuba
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  settings.py: |
    import os

    from snuba.settings import *

    env = os.environ.get

    DEBUG = env("DEBUG", "0").lower() in ("1", "true")

    # Clickhouse Options
    CLUSTERS[0]["host"] = env("CLICKHOUSE_HOST", {{ include "sentry.clickhouse.host" . | quote }})
    CLUSTERS[0]["port"] = int({{ include "sentry.clickhouse.port" . }})
    CLUSTERS[0]["http_port"] = int({{ include "sentry.clickhouse.http_port" . }})
    CLUSTERS[0]["database"] = env("CLICKHOUSE_DATABASE", "default")
    CLUSTERS[0]["user"] = env("CLICKHOUSE_USER", "default")
    CLUSTERS[0]["password"] = env("CLICKHOUSE_PASSWORD", "")
    # FIXME: Snuba will be able to migrate multi node clusters in the future
    CLUSTERS[0]["single_node"] = env("CLICKHOUSE_SINGLE_NODE", "false").lower() == "true"

    # Redis Options
    REDIS_HOST = {{ template "redis.fullname" . }}
    REDIS_PORT = "6379"
    REDIS_PASSWORD = { secretKeyRef: { name: {{ template "redis.fullname" . }}, key: redis-password } }
    REDIS_DB = int(env("REDIS_DB", 1))

{{ .Values.config.snubaSettingsPy | indent 4 }}
