apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbolicator
  labels:
    app: symbolicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symbolicator
  template:
    metadata:
      labels:
        app: symbolicator
    spec:
      containers:
      - name: symbolicator
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ required ".Values.image.symbolicator.repository is missing" .Values.image.symbolicator.repository }}:{{ required ".Values.image.symbolicator.tag is missing" .Values.image.symbolicator.tag }}"
        imagePullPolicy: {{ .Values.image.symbolicator.pullPolicy }}
        args: ["run", "-c", "/etc/symbolicator/config.yml"]
        ports:
        - containerPort: 3021
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthcheck
            port: {{ template "symbolicator.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.symbolicator.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthcheck
            port: {{ template "symbolicator.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.symbolicator.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
