apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-post-process-forward
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-post-process-forward
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-post-process-forward
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}-post-process-forward
        image: "{{required ".Values.global.registry is missing" .Values.global.registry }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sentry", "run", "post-process-forwarder", "--commit-batch-size", "{{ default "1" .Values.sentry.postProcessForward.commitBatchSize }}"]
        env:
{{ include "env-vars" . | indent  10 }}
        resources:
          requests:
            cpu: {{ .Values.sentry.resources.requests.cpu | quote }}
            memory: {{ .Values.sentry.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.sentry.resources.limits.cpu | quote }}
            memory: {{ .Values.sentry.resources.limits.memory | quote }}
