{{- if .Values.sentry.web.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}-sentry-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}-web
  minReplicas: {{ .Values.sentry.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.web.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.sentry.web.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
