apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-relay
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: {{ .Values.service.name }}-relay
  selector:
    app: {{ template "fullname" . }}
    role: relay
