apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-relay
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ template "relay.port" . }}
    targetPort: {{ template "relay.port" }}
    protocol: TCP
    name: {{ .Values.service.name }}-relay
  selector:
    app: {{ template "fullname" . }}
    role: relay
