{{- $domain := printf "limes-3.%s.%s" .Values.global.region .Values.global.tld -}}

kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: limes-api-ccloud
  labels:
    app: limes-api
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"

spec:
  tls:
    - secretName: limes-api-ccloud
      hosts: [ {{ $domain }} ]
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: limes-api-ccloud
                port:
                  number: 80
