apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: openstack-performance
type: Opaque
stringData:
  ssh: |
    {{ .Values.ssh_key | quote }}
  known_hosts: |
    {{ .Values.known_hosts | quote }}
