apiVersion: v1
kind: Service
metadata:
  name: openstack-performance
  namespace: openstack-performance
  annotations:
    loadbalancer.openstack.org/default-tls-container-ref: >-
      https://keymanager-3.qa-de-1.cloud.sap:443/v1/secrets/af30d635-6a1f-437c-9f34-cc4f61bdcec1
    loadbalancer.openstack.org/x-forwarded-for: 'true'
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
      nodePort: 31159
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8089
      nodePort: 31160
  selector:
    app: openstack-performance
