apiVersion: v1
kind: Service
metadata:
  name: openstack-performance
  namespace: openstack-performance
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: openstack-performance
