# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId:
  application: 101
  monitoring: 3000
  proxy: 3100
groupId:
  application: 101
  monitoring: 3000
  proxy: 3100

# namePrefix:
#   application: "mariadb-g" #used for pods, services etc. (default mariadb-g)
#   proxy: "proxysql" #used for pods, services etc. (default proxysql)
cleanOsCacheAtStartup: false #https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html?highlight=drop_caches#drop-caches (default false, only useful for benchmarking)
scripts:
  maxRetries: 20 #how many times should script functions retry before failing(default 10)
  waitTimeBetweenRetriesInSeconds: 6 #how long should script functions wait between retries (default 6)
  logLevel: debug # info(default) or debug
  maxAllowedTimeDifferenceFactor: 12 #to multiply with readinessProbe.timeoutSeconds.application as the maximum allowed time difference between nodes for the last sequence number configmap update (default 3)
  useTimeDifferenceForSeqnoCheck: false #fail if time difference between nodes for the last sequence number configmap update is too big
monitoring:
  prometheus:
    instance: prometheus #name of the Prometheus instance that should pull metrics
  mysqld_exporter:
    enabled: false #enable the Prometheus MySQL exporter as sidecar container https://github.com/prometheus/mysqld_exporter
    metricsPort: 9104
  elasticBeatsAutoDiscoveryAnnotations:
    enabled: false #add annotations to allow automatic configuration of Elastic Beats agents https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
proxy:
  enabled: false #use ProxySQL in front of the MariaDB Galera pods to reduce the service downtimes for the clients

# command:
#   application:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
#   monitoring:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
# job:
#   - "sh"
#   - "-c"
#   - "/bin/sleep 3600"
#   proxy:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"

# Docker image
image:
  os:
    registry: keppel.eu-nl-1.cloud.sap
    project: octobus
    applicationname: ubuntu
    applicationversion: 20.04
    imageversion: 0.3.67
    pullPolicy: IfNotPresent
    pullSecret: false
  application:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: mariadb-galera
    applicationversion: 10.5.17
    imageversion: 0.1.1
    pullPolicy: Always
    pullSecret: false
  monitoring:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: mysqld_exporter
    applicationversion: 0.14.0
    imageversion: 0.1.1
    pullPolicy: Always
    pullSecret: false
  proxy:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: proxysql
    applicationversion: 2.4.3
    imageversion: 0.1.1
    pullPolicy: Always
    pullSecret: false

initContainers:
  increaseMapCount:
    securityContext:
      privileged: true
      runAsUser: 0
  tcpKeepAlive:
    securityContext:
      privileged: true
      runAsUser: 0
  cleanoscache:
    securityContext:
      privileged: true
      runAsUser: 0

# network services
services:
  application:
    - name: backend
      type: ClusterIP
      headless: true
      #https://mariadb.com/kb/en/configuring-mariadb-galera-cluster/#network-ports
      ports:
        - name: galera
          port: 4567
          targetPort: 4567
          protocol: TCP
        - name: ist #http://galeracluster.com/library/documentation/galera-parameters.html#ist-recv-addr
          port: 4568
          targetPort: 4568
          protocol: TCP
        - name: sst #https://mariadb.com/kb/en/introduction-to-state-snapshot-transfers-ssts/
          port: 4444
          targetPort: 4444
          protocol: TCP
      sessionAffinity: None
    - name: frontend
      type: ClusterIP
      headless: false
      ports:
        - name: mysql
          port: 3306
          targetPort: 3306
          protocol: TCP
      sessionAffinity: None
  proxy:
    - name: backend
      type: ClusterIP
      headless: true
      ports:
        - name: proxy #https://proxysql.com/Documentation/global-variables/admin-variables/#admin-mysql_ifaces
          port: 6032
          targetPort: 6032
          protocol: TCP
        - name: rest #https://proxysql.com/Documentation/global-variables/admin-variables/#admin-mysql_ifaces
          port: 6070
          targetPort: 6070
          protocol: TCP
      sessionAffinity: None
    - name: frontend
      type: ClusterIP
      headless: false
      ports:
        - name: proxy #https://proxysql.com/Documentation/global-variables/mysql-variables/#mysql-interfaces
          port: 3306
          targetPort: 6033
          protocol: TCP
      sessionAffinity: None

# Storage
volumeMounts:
  application:
    - name: data
      claimName: mariadb
      mountPath: /opt/mariadb/data
      type: persistentVolume
    - name: log
      claimName: marialog
      mountPath: /opt/mariadb/log
      type: persistentVolume
    - name: cert-wildcard
      mountPath: /opt/mariadb/etc/certs
      type: secret
      readOnly: true
  proxy:
    - name: data
      claimName: proxysql
      mountPath: /opt/proxysql/data
      type: persistentVolume

volumeClaimTemplates:
  - name: mariadb
    accessModes: [ReadWriteOnce]
    capacity: 1Gi
    storageClassName: false #optional: currently cinder and nfs are supported
  - name: marialog
    accessModes: [ReadWriteOnce]
    capacity: 10Gi
  - name: proxysql
    accessModes: [ReadWriteOnce]
    capacity: 128Mi

# Resource limits per container
resourceLimits:
  cpu:
    application: 2
    monitoring: 0.5
    job: 0.5
    proxy: 0.5
  memory:
    application: 1024Mi
    monitoring: 48Mi
    job: 48Mi
    proxy: 256Mi

# Deployment rules
replicas:
  application: 3 #only uneven values are allowed to avoid a split brain cluster state
  proxy: 3 #only uneven values are allowed to avoid a split brain cluster state
maxUnavailable: 1
maxSurge: 1
hpa:
  enabled: false
  minReplicas: 3
  maxReplicas: 3
  maxCpuPercent: 50
UpdateStrategy: RollingUpdate
podManagementPolicy: Parallel
revisionHistoryLimit: 3
terminationGracePeriodSeconds: 600
regional: false
backoffLimit: 12 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
activeDeadlineSeconds: 600 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup
ttlSecondsAfterFinished: 7200 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically
jobRestartPolicy: OnFailure #https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures

#Container Health Checks
startupProbe:
  initialDelaySeconds:
    application: 15
    proxy: 15
  periodSeconds:
    application: 10
    proxy: 10
  failureThreshold:
    application: 12
    proxy: 12
  timeoutSeconds:
    application: 20
    proxy: 20
livenessProbe:
  initialDelaySeconds:
    application: 15
    monitoring: 5
    proxy: 15
  periodSeconds:
    application: 30
    monitoring: 30
    proxy: 30
  failureThreshold:
    application: 4
    monitoring: 4
    proxy: 4
  timeoutSeconds:
    application: 20
    monitoring: 20
    proxy: 20
readinessProbe:
  initialDelaySeconds:
    application: 30
    monitoring: 10
    proxy: 30
  periodSeconds:
    application: 20
    monitoring: 20
    proxy: 20
  successThreshold:
    application: 1
    monitoring: 1
    proxy: 1
  failureThreshold:
    application: 3
    monitoring: 3
    proxy: 3
  timeoutSeconds:
    application: 10
    monitoring: 10
    proxy: 10

env:
  MARIADB_CLUSTER_NAME:
    value: eu-de-1.nova
    containerType:
      - application
  MARIADB_ROOT_USER:
    secretName: db-full-auth
    secretKey: username
    containerType:
      - application
      - job
      - proxy
  MARIADB_ROOT_PASSWORD:
    secretName: db-full-auth
    secretKey: password
    containerType:
      - application
      - job
      - proxy
  GALERA_SST_USER:
    secretName: ga-sync-auth
    secretKey: username
    containerType:
      - application
  GALERA_SST_PASSWORD:
    secretName: ga-sync-auth
    secretKey: password
    containerType:
      - application
  MARIADB_MONITORING_USER:
    secretName: db-mon-auth
    secretKey: username
    containerType:
      - application
      - monitoring
      - job
  MARIADB_MONITORING_PASSWORD:
    secretName: db-mon-auth
    secretKey: password
    containerType:
      - application
      - monitoring
      - job
  MARIADB_MONITORING_CONNECTION_LIMIT:
    value: 6
    containerType:
      - application
      - job
  WEB_TELEMETRY_PATH:
    value: /metrics
    containerType:
      - monitoring
  PROXYSQL_ADMIN_USER:
    secretName: proxy-full-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_ADMIN_PASSWORD:
    secretName: proxy-full-auth
    secretKey: password
    containerType:
      - proxy
  PROXYSQL_MONITOR_USER:
    secretName: db-mon-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_MONITOR_PASSWORD:
    secretName: db-mon-auth
    secretKey: password
    containerType:
      - proxy
  PROXYSQL_STATS_USER:
    secretName: proxy-stats-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_STATS_PASSWORD:
    secretName: proxy-stats-auth
    secretKey: password
    containerType:
      - proxy
  PROXYSQL_RESTAPI_ENABLED:
    value: true
    containerType:
      - proxy
  OPENSTACK_CITEST_PASSWORD:
    secretName: db-oslodb-auth
    secretKey: password
    containerType:
      - job
  SYSBENCH_PASSWORD:
    secretName: db-sysbench-auth
    secretKey: password
    containerType:
      - job

mariadb:
  binLogDir: log #if not defined the data dir will be used. Needs a log volume mount to be configured too
  galera:
    debug: false #https://galeracluster.com/library/documentation/galera-parameters.html#debug
    waitForPrimaryTimeoutInSeconds: 60 #https://galeracluster.com/library/documentation/galera-parameters.html#pc.wait_prim_timeout
    logLevel: info #info(default) or debug https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_debug
    pcrecovery: false #https://galeracluster.com/library/documentation/pc-recovery.html
    gcache.recover: false #
    sst_method: rsync #rsync or mariabackup(also requires GALERA_SST_USER and GALERA_SST_PASSWORD)
    slaveThreads: 16 #https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-slave-threads
