# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId:
  application: 101
  monitoring: 3000
  proxy: 3100
groupId:
  application: 101
  monitoring: 3000
  proxy: 3100

namePrefix:
  application: false #used for pods, services etc. (default mariadb-g)
  proxy: false #used for pods, services etc. (default proxysql)
cleanOsCacheAtStartup: false #https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html?highlight=drop_caches#drop-caches (default false, only useful for benchmarking)
scripts:
  maxRetries: 20 #how many times should script functions retry before failing(default 10)
  waitTimeBetweenRetriesInSeconds: 6 #how long should script functions wait between retries (default 6)
  logLevel: debug # info(default) or debug
  maxAllowedTimeDifferenceFactor: 12 #to multiply with readinessProbe.timeoutSeconds.application as the maximum allowed time difference between nodes for the last sequence number configmap update (default 3)
  useTimeDifferenceForSeqnoCheck: true #fail if time difference between nodes for the last sequence number configmap update is too big
mariadb:
  autostart: true #default=true, run the default entrypoint.sh script or just sleep to be able to troubleshoot and debug
  binLogDir: log #if not defined the data dir will be used. Needs a log volume mount to be configured too
  binLogSync: 1 #default=0 (1 for ACID compliance) https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#sync_binlog
  innodbFlushLogAtTrxCommit: 1 #default=0 (1 for ACID compliance) https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  performance_schema: false #https://mariadb.com/kb/en/performance-schema-overview/
  errorLogWarningVerbosity: 1 #default=2, https://mariadb.com/kb/en/error-log/#configuring-the-error-log-verbosity
  asyncReplication:
    enabled: false
    resetConfig: false #reset the replica configuration. Use with care, because the currently used GTID binlog position value will be deleted. That can cause missing or duplicate data on the replica later
    autostart: false #default=false, start configured slave during database node startup https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_restart_slave
    primaryHost: false #Hostname or IP of the replication source https://mariadb.com/kb/en/change-master-to/#master_host
    slaveReplicaThreads: false #default=1, https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#slave_parallel_threads
  galera:
    debug: false #https://galeracluster.com/library/documentation/galera-parameters.html#debug
    waitForPrimaryTimeoutInSeconds: 60 #https://galeracluster.com/library/documentation/galera-parameters.html#pc.wait_prim_timeout
    logLevel: info #info(default) or debug https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_debug
    pcrecovery: false #https://galeracluster.com/library/documentation/pc-recovery.html
    gcache.recover: false #until https://github.com/codership/galera/issues/624 is fixed
    sst_method: rsync #rsync or mariabackup(also requires GALERA_SST_USER and GALERA_SST_PASSWORD)
    slaveThreads: 16 #https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-slave-threads
    gtidDomainId: 1 #default = 1, must be a positive integer https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_gtid_domain_id
    gtidDomainIdCount: 1 #default = 1, how many Galera cluster instances will be connected. Used for async primary/replica setups
    gtidStrictMode: false #https://mariadb.com/kb/en/gtid/#gtid_strict_mode
    backup:
      enabled: true
      openstack: #https://docs.openstack.org/python-openstackclient/zed/cli/authentication.html
        authurl: https://identity-3.eu-de-2.cloud.sap:443/v3
        region: eu-de-2
        projectname: cc-demo
        tenantname: monsoon3
        container: mariadb-galera-backup
      restic:
        compression: auto #https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#compression
        packsizeInMB: 128 #https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#pack-size keep in mind the 5GB Swift object size limit and the potential object count quota limit
        unlockRepo: false #default=false https://restic.readthedocs.io/en/stable/manual_rest.html?highlight=unlock
        pruneBackups: false #default=false https://restic.readthedocs.io/en/stable/060_forget.html?highlight=prune#removing-backup-snapshots
        keep: #https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy
          last: 2
          hourly: 24
          daily: 7
          weekly: 4
          monthly: 12
          yearly: 2
monitoring:
  prometheus:
    instance: prometheus #name of the Prometheus instance that should pull metrics
  mysqld_exporter:
    autostart: true
    enabled: false #enable the Prometheus MySQL exporter as sidecar container https://github.com/prometheus/mysqld_exporter
    metricsPort: 9104
  elasticBeatsAutoDiscoveryAnnotations:
    enabled: false #(not yet implemented) add annotations to allow automatic configuration of Elastic Beats agents https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
proxy:
  enabled: false #use ProxySQL in front of the MariaDB Galera pods to reduce the service downtimes for the clients
  restapi:
    enabled: true #https://proxysql.com/documentation/REST-API/
  adminui:
    enabled: true #https://proxysql.com/documentation/http-web-server/
    verbosity: 0 #https://proxysql.com/documentation/global-variables/admin-variables/#admin-web_verbosity
  queryRules:
    genericReadWriteSplit:
      enabled: true #The "Generic Read/Write split using regex" section in https://proxysql.com/documentation/proxysql-read-write-split-howto/

# Docker image
image:
  os:
    registry: keppel.eu-nl-1.cloud.sap
    project: octobus
    applicationname: ubuntu
    applicationversion: 20.04
    imageversion: 0.3.67
    pullPolicy: IfNotPresent
    pullSecret: false
  application:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: mariadb-galera
    applicationversion: 10.5.17
    imageversion: 0.2.4
    pullPolicy: Always
    pullSecret: false
  monitoring:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: mysqld_exporter
    applicationversion: 0.14.0
    imageversion: 0.1.1
    pullPolicy: Always
    pullSecret: false
  proxy:
    registry: keppel.eu-de-1.cloud.sap
    project: ccloud
    applicationname: proxysql
    applicationversion: 2.4.4
    imageversion: 0.1.2
    pullPolicy: Always
    pullSecret: false

initContainers:
  increaseMapCount:
    securityContext:
      privileged: true
      runAsUser: 0
  tcpKeepAlive:
    securityContext:
      privileged: true
      runAsUser: 0
  cleanoscache:
    securityContext:
      privileged: true
      runAsUser: 0

# network services
services:
  application:
    backend:
      type: ClusterIP
      headless: true
      #https://mariadb.com/kb/en/configuring-mariadb-galera-cluster/#network-ports
      ports:
        galera:
          port: 4567
          targetPort: 4567
          protocol: TCP
        ist: #http://galeracluster.com/library/documentation/galera-parameters.html#ist-recv-addr
          port: 4568
          targetPort: 4568
          protocol: TCP
        sst: #https://mariadb.com/kb/en/introduction-to-state-snapshot-transfers-ssts/
          port: 4444
          targetPort: 4444
          protocol: TCP
      sessionAffinity: None
    frontend:
      type: ClusterIP #ClusterIP/LoadBalancer
      headless: false
      ports:
        mysql:
          port: 3306
          targetPort: 3306
          protocol: TCP
      sessionAffinity: ClientIP
      sessionAffinityClientIpTimeoutSeconds: 28800
  proxy:
    backend:
      type: ClusterIP
      headless: true
      #https://proxysql.com/Documentation/global-variables/admin-variables/#admin-mysql_ifaces
      ports:
        proxy:
          port: 6032
          targetPort: 6032
          protocol: TCP
        restapi: #https://proxysql.com/documentation/REST-API/
          port: 6070
          targetPort: 6070
          protocol: TCP
        adminui: #https://proxysql.com/documentation/http-web-server/
          port: 6080
          targetPort: 6080
          protocol: TCP
      sessionAffinity: None
    frontend:
      type: ClusterIP #ClusterIP/LoadBalancer
      headless: false
      ports:
        proxy: #https://proxysql.com/Documentation/global-variables/mysql-variables/#mysql-interfaces
          port: 3306
          targetPort: 6033
          protocol: TCP
      sessionAffinity: None


# Storage
volumeMounts:
  application:
    - name: data
      claimName: mariadb
      mountPath: /opt/mariadb/data
      type: persistentVolume
    - name: log
      claimName: marialog
      mountPath: /opt/mariadb/log
      type: persistentVolume
    - name: cert-wildcard
      mountPath: /opt/mariadb/etc/certs
      type: secret
      readOnly: true
  proxy:
    - name: data
      claimName: proxysql
      mountPath: /opt/proxysql/data
      type: persistentVolume

volumeClaimTemplates:
  - name: mariadb
    accessModes: [ReadWriteOnce]
    capacity: 10Gi
    storageClassName: false #optional: currently cinder and nfs are supported
  - name: marialog
    accessModes: [ReadWriteOnce]
    capacity: 30Gi
  - name: proxysql
    accessModes: [ReadWriteOnce]
    capacity: 128Mi

# Resource limits per container
resourceLimits:
  cpu:
    application: 2
    monitoring: 0.5
    job: 0.5
    cronjob: 2
    proxy: 2
  memory:
    application: 1024Mi
    monitoring: 48Mi
    job: 48Mi
    cronjob: 1024Mi
    proxy: 256Mi

# Deployment rules
replicas:
  application: 3 #only uneven values are allowed to avoid a split brain cluster state
  proxy: 3 #only uneven values are allowed to avoid a split brain cluster state
maxUnavailable: 1
maxSurge: 1
hpa:
  enabled: false
  minReplicas: 3
  maxReplicas: 3
  maxCpuPercent: 50
UpdateStrategy: RollingUpdate
podManagementPolicy: Parallel
revisionHistoryLimit: 3
terminationGracePeriodSeconds: 600
regional: false
job:
  mariadbconfig:
    backoffLimit: 12 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
    activeDeadlineSeconds: 600 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup
    ttlSecondsAfterFinished: 7200 #https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically
    jobRestartPolicy: OnFailure #https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
  mariadbbackup:
    schedule: "*/15 * * * *" #https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule & https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
    jobRestartPolicy: OnFailure #https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
    concurrencyPolicy: Forbid #https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
    successfulJobsHistoryLimit: 1 #https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits
    failedJobsHistoryLimit: 1 #https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

#Container Health Checks
startupProbe:
  initialDelaySeconds:
    application: 15
    proxy: 15
  periodSeconds:
    application: 10
    proxy: 10
  failureThreshold:
    application: 12
    proxy: 12
  timeoutSeconds:
    application: 20
    proxy: 20
livenessProbe:
  initialDelaySeconds:
    application: 15
    monitoring: 5
    proxy: 15
  periodSeconds:
    application: 30
    monitoring: 30
    proxy: 30
  failureThreshold:
    application: 4
    monitoring: 4
    proxy: 4
  timeoutSeconds:
    application: 20
    monitoring: 20
    proxy: 20
readinessProbe:
  initialDelaySeconds:
    application: 30
    monitoring: 10
    proxy: 30
  periodSeconds:
    application: 20
    monitoring: 20
    proxy: 20
  successThreshold:
    application: 1
    monitoring: 1
    proxy: 1
  failureThreshold:
    application: 3
    monitoring: 3
    proxy: 3
  timeoutSeconds:
    application: 10
    monitoring: 10
    proxy: 10

env:
  MARIADB_CLUSTER_NAME:
    value: eu-de-1.nova
    containerType:
      - application
      - cronjob
  MARIADB_ROOT_USER:
    secretName: db-full-auth
    secretKey: username
    containerType:
      - application
      - job
      - proxy
      - cronjob
  MARIADB_ROOT_PASSWORD:
    secretName: db-full-auth
    secretKey: password
    containerType:
      - application
      - job
      - proxy
      - cronjob
  GALERA_SST_USER:
    secretName: ga-sync-auth
    secretKey: username
    containerType:
      - application
      - job
      - proxy
  GALERA_SST_PASSWORD:
    secretName: ga-sync-auth
    secretKey: password
    containerType:
      - application
      - job
      - proxy
  MARIADB_MONITORING_USER:
    secretName: db-mon-auth
    secretKey: username
    containerType:
      - application
      - monitoring
      - job
  MARIADB_MONITORING_PASSWORD:
    secretName: db-mon-auth
    secretKey: password
    containerType:
      - application
      - monitoring
      - job
  MARIADB_MONITORING_CONNECTION_LIMIT:
    value: 6
    containerType:
      - application
      - job
  WEB_TELEMETRY_PATH:
    value: /metrics
    containerType:
      - monitoring
  PROXYSQL_ADMIN_USER:
    secretName: proxy-full-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_ADMIN_PASSWORD:
    secretName: proxy-full-auth
    secretKey: password
    containerType:
      - proxy
  PROXYSQL_MONITOR_USER:
    secretName: db-mon-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_MONITOR_PASSWORD:
    secretName: db-mon-auth
    secretKey: password
    containerType:
      - proxy
  PROXYSQL_STATS_USER:
    secretName: proxy-stats-auth
    secretKey: username
    containerType:
      - proxy
  PROXYSQL_STATS_PASSWORD:
    secretName: proxy-stats-auth
    secretKey: password
    containerType:
      - proxy
  OPENSTACK_CITEST_USERNAME:
    secretName: db-oslodb-auth
    secretKey: username
    containerType:
      - job
      - proxy
  OPENSTACK_CITEST_PASSWORD:
    secretName: db-oslodb-auth
    secretKey: password
    containerType:
      - job
      - proxy
  SYSBENCH_USERNAME:
    secretName: db-sysbench-auth
    secretKey: username
    containerType:
      - job
      - proxy
  SYSBENCH_PASSWORD:
    secretName: db-sysbench-auth
    secretKey: password
    containerType:
      - job
      - proxy
  OS_USERNAME:
    secretName: restic-swift-auth
    secretKey: username
    containerType:
      - cronjob
  OS_PASSWORD:
    secretName: restic-swift-auth
    secretKey: password
    containerType:
      - cronjob
  RESTIC_PASSWORD:
    secretName: restic-repo-auth
    secretKey: password
    containerType:
      - cronjob
  REPLICA_USERNAME:
    secretName: replica-primary-auth
    secretKey: username
    containerType:
      - application
      - job
      - proxy
  REPLICA_PASSWORD:
    secretName: replica-primary-auth
    secretKey: password
    containerType:
      - application
      - job
      - proxy
#command:
#   application:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
#   monitoring:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
#    job:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
#   cronjob:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
#   proxy:
#     - "sh"
#     - "-c"
#     - "/bin/sleep 3600"
