{{- $root := . }}
{{- range $target := .Values.global.targets }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    ccloud/support-group: observability
  name: {{ include "vropsInventory.fullName" (list $target $root) }}
  namespace: vmware-monitoring
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: {{ include "vropsInventory.fullName" (list $target $root) }}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledValues: RequestsOnly
        controlledResources:
          - cpu
          - memory
{{- end }}
