{{- if .Values.enabled }}
{{- if .Values.traefik.enabled }}
{{- $root := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: {{ include "thanos.fullName" . }}-grpc
  annotations:
    disco: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    {{- range $host := $root.Values.grpcIngress.hosts }}
    - host: {{ $host }}-grpc.{{ $root.Values.global.region }}.{{ $root.Values.global.tld }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name:  {{ include "thanos.fullName" $root }}-query
              port:
                number: 10901
    {{- end }}
  tls:
    - secretName: tls-{{ include "thanos.grpcURL" $root | replace "." "-" }}
      hosts:
        {{- range $host := $root.Values.grpcIngress.hosts }}
        - {{ $host }}-grpc.{{ $root.Values.global.region }}.{{ $root.Values.global.tld }}
        {{- end }}
        {{- range $host := $root.Values.grpcIngress.hostsFQDN }}
        - {{ $host }}
        {{- end }}
{{- end }}
{{- end }}