{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if and (hasKey $.Values.mariadb "wipeDataAndLog") ($.Values.mariadb.wipeDataAndLog) }}
{{- else if and (hasKey $.Values.mariadb.galera.restore "kopia") ($.Values.mariadb.galera.restore.kopia.enabled) }}
{{- else if and (hasKey $.Values.monitoring.mysqld_exporter "autostart") (not $.Values.monitoring.mysqld_exporter.autostart) }}
{{- else if $.Values.monitoring.mysqld_exporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ (include "nodeNamePrefix" (dict "global" $ "component" "application")) }}-alerts
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    component: "application"
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    prometheus: {{ $.Values.monitoring.prometheus.instance | default "prometheus" | quote }}
spec:
  groups:
{{ include (print .Template.BasePath "alerts/mariadb.yaml") . | indent 2 }}
{{- end }}
---
{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if and (hasKey $.Values.mariadb "wipeDataAndLog") ($.Values.mariadb.wipeDataAndLog) }}
{{- else if and (hasKey $.Values.mariadb.galera.restore "kopia") ($.Values.mariadb.galera.restore.kopia.enabled) }}
{{- else if and (hasKey $.Values.monitoring.mysqld_exporter "autostart") (not $.Values.monitoring.mysqld_exporter.autostart) }}
{{- else if and $.Values.proxy.enabled $.Values.monitoring.proxy.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ (include "nodeNamePrefix" (dict "global" $ "component" "proxy")) }}-alerts
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    component: "proxy"
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    prometheus: {{ $.Values.monitoring.prometheus.instance | default "prometheus" | quote }}
spec:
  groups:
{{ include (print .Template.BasePath "alerts/proxysql.yaml") . | indent 2 }}
{{- end }}
---
{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if and (hasKey $.Values.mariadb "wipeDataAndLog") ($.Values.mariadb.wipeDataAndLog) }}
{{- else if and (hasKey $.Values.mariadb.galera.restore "kopia") ($.Values.mariadb.galera.restore.kopia.enabled) }}
{{- else if and (hasKey $.Values.monitoring.mysqld_exporter "autostart") (not $.Values.monitoring.mysqld_exporter.autostart) }}
{{- else if and (and (hasKey $.Values.mariadb.galera "backup") ($.Values.mariadb.galera.backup.enabled)) (and (hasKey $.Values.mariadb.galera.backup "kopia") ($.Values.mariadb.galera.backup.kopia.enabled)) $.Values.monitoring.kopia.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  {{ include "commonPrefix" $ }}backup-kopiaserver-alerts
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    component: "kopiaserver"
    release: {{ $.Release.Name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    prometheus: {{ $.Values.monitoring.prometheus.instance | default "prometheus" | quote }}
spec:
  groups:
{{ include (print .Template.BasePath "alerts/kopia.yaml") . | indent 2 }}
{{- end }}