---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cnf
  namespace: {{ $.Release.Namespace }}
data:
{{- range $int, $err := until ($.Values.replicas|int) }}
  my.cnf.{{ $.Release.Name }}-{{ $int }}.tpl: |-
    [mariadb]
    #https://mariadb.com/kb/en/galera-cluster-system-variables/
    #https://galeracluster.com/library/documentation/weighted-quorum.html#wq-three-nodes
    wsrep-provider=/usr/lib/libgalera_smm.so
    binlog_format=ROW
    log-bin=/opt/mariadb/data/mysql-bin.log
    expire_logs_days=1
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    {{- range $envKey, $envValue := $.Values.env }}
      {{- if eq $envValue.name "MARIADB_CLUSTER_NAME"}}
    wsrep-cluster-name={{ $envValue.value }}
      {{- end }}
    {{- end }}
    {{- range $servicesKey, $servicesValue := $.Values.services }}
      {{- if eq $servicesValue.name "be"}}
        {{- range $portsKey, $portsValue := $servicesValue.ports }}
          {{- if eq $portsValue.name "galera"}}
            {{- $nodeNames := list -}}
            {{- range $int, $err := until ($.Values.replicas|int) }}
              {{- $nodeNames = (printf "g%d.%s.svc.cluster.local:%d" $int $.Release.Namespace ($portsValue.port | int)) | append $nodeNames -}}
            {{- end }}
    wsrep_cluster_address={{ (printf "gcomm://%s,%s-be.%s.svc.cluster.local:%d" (join "," $nodeNames) $.Release.Name $.Release.Namespace ($portsValue.port | int)) }}
          {{- else if eq $portsValue.name "ist" }}
    wsrep_provider_options={{ (printf "ist.recv_addr=${CONTAINER_IP}:%d;pc.wait_prim_timeout=PT%dS;gcache.recover=yes;pc.weight=${PC_WEIGHT_%d}" ($portsValue.port | int) ($.Values.mariadb.galera.waitForPrimaryTimeoutInSeconds | default 30 | int) $int) }}
          {{- else if eq $portsValue.name "sst" }}
    wsrep-sst-receive-address={{ (printf "${CONTAINER_IP}:%d" ($portsValue.port | int)) }}
    wsrep_node_address=${CONTAINER_IP}
    wsrep_node_name={{ $.Release.Name }}-{{ $int }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    wsrep-on=1
    #wsrep_sst_method=mariabackup
    #wsrep_sst_auth=${GALERA_SST_USER}:${GALERA_SST_USER}

{{- end }}