{{- if and ($.Values.proxy.enabled) (eq $.Values.proxy.type "haproxy") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  {{ include "commonPrefix" $ }}haproxy-config
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/haproxy/haproxy.conf").AsConfig . | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  {{ include "commonPrefix" $ }}haproxy-probes-sh
  labels:
    app: {{ $.Release.Name }}
data:
  readiness.sh: |
{{ tpl (.Files.Glob "scripts/haproxy/readiness.sh").AsConfig . | indent 4 }}
  liveness.sh: |
{{ tpl (.Files.Glob "scripts/haproxy/liveness.sh").AsConfig . | indent 4 }}
{{- end }}
