---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: hooks-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "config/pre-stop-hook.sh").AsConfig . | indent 2 }}

{{ tpl (.Files.Glob "config/post-start-hook.sh").AsConfig . | indent 2 }}
