{{- if $.Values.proxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  proxysql-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/entrypoint.sh").AsConfig . | indent 2 }}
{{- end }}
