---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: mariadb-job-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/mariadb-galera/entrypoint-job.sh").AsConfig . | indent 2 }}
