{{- if $.Values.proxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  proxysql-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/entrypoint.sh").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  proxysql-common-functions-extended-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/common-functions-extended.sh").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-probes-sh
  namespace: {{ $.Release.Namespace }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/startup.sh").AsConfig . | indent 2 }}
{{ tpl (.Files.Glob "scripts/proxysql/liveness.sh").AsConfig . | indent 2 }}
{{ tpl (.Files.Glob "scripts/proxysql/readiness.sh").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: proxysql-hooks-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/pre-stop-hook.sh").AsConfig . | indent 2 }}
{{ tpl (.Files.Glob "scripts/proxysql/post-start-hook.sh").AsConfig . | indent 2 }}
{{- end }}
