---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  checks-sh
  namespace: {{ $.Release.Namespace }}
data:
  liveness.sh: |-
    #!/usr/bin/env bash
    set +e
    set -u
    set -o pipefail
    set +x

    timeout {{ $.Values.livenessProbe.timeoutSeconds }} bash -c "</dev/tcp/${CONTAINER_IP}/${MYSQL_PORT}"
    if [ $? -eq 0 ]; then
      echo 'MariaDB MySQL API reachable'
    else
      echo 'MariaDB MySQL API not reachable'
      exit 1
    fi

    timeout {{ $.Values.livenessProbe.timeoutSeconds }} bash -c "</dev/tcp/${CONTAINER_IP}/${GALERA_PORT}"
    if [ $? -eq 0 ]; then
      echo 'MariaDB Galera API reachable'
    else
      echo 'MariaDB Galera API not reachable'
      exit 1
    fi

  readiness.sh: |-
    #!/usr/bin/env bash
    set +e
    set -u
    set -o pipefail
    set +x

    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf -u root -h localhost --database=mysql --execute='STATUS;' | grep 'Server version:' | grep --silent "${SOFTWARE_VERSION}"
    if [ $? -eq 0 ]; then
      echo 'MariaDB MySQL API usable'
    else
      echo 'MariaDB MySQL API not usable'
      exit 1
    fi
