---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  mariadb-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/mariadb-galera/entrypoint-galera.sh").AsConfig . | indent 2 }}
{{- if $.Values.monitoring.mysqld_exporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  job-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/mariadb-galera/entrypoint-job.sh").AsConfig . | indent 2 }}
{{- end }}
{{- if $.Values.monitoring.mysqld_exporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  monitoring-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/mysqld_exporter/entrypoint.sh").AsConfig . | indent 2 }}
{{- end }}
{{- if $.Values.proxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  proxysql-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/proxysql/entrypoint.sh").AsConfig . | indent 2 }}
{{- end }}