---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Release.Namespace }}
  name: mariadbbackup-cronjob-entrypoint-sh
  labels:
    app: {{ $.Release.Name }}
data:
{{ tpl (.Files.Glob "scripts/mariadb-galera/entrypoint-backup.sh").AsConfig . | indent 2 }}
