{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if and (hasKey $.Values.mariadb.galera "restore") ($.Values.mariadb.galera.restore.enabled) }}
{{- else if and (hasKey $.Values.mariadb "wipeDataAndLog") ($.Values.mariadb.wipeDataAndLog) }}
{{- else if and (hasKey $.Values.mariadb.galera "backup") ($.Values.mariadb.galera.backup.enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ (include "nodeNamePrefix" (dict "global" $ "component" "application")) }}-backup-{{ randAlphaNum 8 | lower }}
  labels:
    app: {{ $.Release.Name }}
    release: {{ $.Release.Name }}
spec:
  schedule: {{ $.Values.job.mariadbbackup.schedule | default "05 23 * * *" | quote }}
  concurrencyPolicy: {{ $.Values.job.mariadbbackup.concurrencyPolicy | default "Forbid" | quote }}
  successfulJobsHistoryLimit: {{ $.Values.job.mariadbbackup.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ $.Values.job.mariadbbackup.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $.Release.Name }}
            release: {{ $.Release.Name }}
          annotations:
            checksum/entrypoint.sh: {{ include (print $.Template.BasePath "/configmap-mariadbbackup-cronjob-entrypoint.sh.yaml") $ | sha256sum }}
            checksum/common-functions-extended.sh: {{ include (print $.Template.BasePath "/configmap-mariadb-common-functions-extended.sh.yaml") $ | sha256sum }}
        spec:
          restartPolicy: {{ $.Values.job.mariadbbackup.jobRestartPolicy | default "OnFailure" | quote }}
          serviceAccount: {{ $.Release.Name }}
          securityContext:
            fsGroup:  {{ $.Values.groupId.application }}
          imagePullSecrets:
          - name: {{ $.Release.Name }}-{{$.Values.image.application.pullSecret}}
          containers:
          - name: backup
            image: "{{ $.Values.image.application.registry }}/{{ $.Values.image.application.project }}/{{ $.Values.image.application.applicationname }}:{{ $.Values.image.application.applicationversion }}-{{ $.Values.image.application.imageversion }}"
            imagePullPolicy: {{ $.Values.image.application.pullPolicy | default "IfNotPresent" | quote }}
            securityContext:
              runAsUser:  {{ $.Values.userId.application }}
              runAsGroup: {{ $.Values.groupId.application }}
            {{- if and ($.Values.command) (hasKey $.Values.command "cronjob") }}
            command:
{{ $.Values.command.cronjob | toYaml | indent 12 }}
            {{- else }}
            command:
              - "sh"
              - "-c"
              - "/opt/mariadb/bin/entrypoint-backup.sh"
            {{- end }}
            env:
            - name: OS_AUTH_URL
              value: {{ required "Values.mariadb.galera.backup.openstack.authurl is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.authurl }}
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_REGION_NAME
              value: {{ required "Values.mariadb.galera.backup.openstack.region is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.region }}
            - name: OS_PROJECT_NAME
              value: {{ required "Values.mariadb.galera.backup.openstack.projectname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.projectname }}
            - name: OS_PROJECT_DOMAIN_NAME
              value: {{ required "Values.mariadb.galera.backup.openstack.tenantname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.tenantname }}
            - name: OS_USER_DOMAIN_NAME
              value: {{ required "Values.mariadb.galera.backup.openstack.tenantname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.tenantname }}
            - name: MYSQL_PORT
              value: {{ (required ".services.application.frontend.ports.mysql.targetPort missing" $.Values.services.application.frontend.ports.mysql.targetPort) | quote }}
            - name: RESTIC_REPOSITORY
              value: {{ (printf "swift:%s:/" (required "Values.mariadb.galera.backup.openstack.container is missing, but required for restic to access the repository." $.Values.mariadb.galera.backup.openstack.container)) | quote }}
            - name: RESTIC_PROGRESS_FPS
              value: {{ $.Values.mariadb.galera.backup.restic.progressFps | default "0.01666" | quote }}
            - name: RESTIC_CACHE_DIR
              value: "/opt/mariadb/run/"
            - name: TMPDIR
              value: "/opt/mariadb/tmp/"
            {{- range $envKey, $envValue := $.Values.env }}
              {{- if (has "cronjob" $envValue.containerType) }}
            - name: {{ $envKey }}
                {{- if $envValue.value }}
              value: {{ $envValue.value | quote }}
                {{- end }}
                {{- if $envValue.secretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-{{ $envValue.secretName }}
                  key: {{ $envValue.secretKey }}
                {{- end }}
              {{- end }}
            {{- end }}
            resources:
              requests:
                cpu: {{ $.Values.resourceLimits.cpu.cronjob | default 0.25 }}
              limits:
                memory: {{ $.Values.resourceLimits.memory.cronjob | default "32Mi" | quote }}
            volumeMounts:
            - name: mariadbbackup-cronjob-entrypoint-sh
              mountPath: /opt/mariadb/bin/entrypoint-backup.sh
              subPath: entrypoint-backup.sh
              readOnly: true
            - name: mariadb-common-functions-extended-sh
              mountPath: /opt/mariadb/bin/common-functions-extended.sh
              subPath: common-functions-extended.sh
              readOnly: true
          volumes:
          {{- range $volumeMountsKey, $volumeMountsValue := $.Values.volumeMounts.application }}
            {{- if $volumeMountsValue.type }}
              {{- if ne $volumeMountsValue.type "persistentVolume" }}
          - name: {{ $volumeMountsKey }}
                {{- if eq $volumeMountsValue.type "secret"}}
            {{ $volumeMountsValue.type }}:
              secretName: {{ $.Release.Name }}-{{ $volumeMountsValue.name }}
                {{- else if eq $volumeMountsValue.type "hostPath" }}
            {{ $volumeMountsValue.type }}:
              path: {{ $volumeMountsValue.hostPath }}
                {{- else }}
              name: {{ $volumeMountsKey }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          - name: mariadbbackup-cronjob-entrypoint-sh
            configMap:
              name: mariadbbackup-cronjob-entrypoint-sh
              defaultMode: 0750
          - name: mariadb-common-functions-extended-sh
            configMap:
              name: mariadb-common-functions-extended-sh
              defaultMode: 0755
{{- end }}