{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if and (hasKey $.Values.mariadb.galera "restore") (not $.Values.mariadb.galera.restore.enabled) }}
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ (include "nodeNamePrefix" (dict "global" $ "component" "application")) }}-restore-{{ randAlphaNum 8 | lower }}
  labels:
    app: {{ $.Release.Name }}
    release: {{ $.Release.Name }}
spec:
  backoffLimit: {{ $.Values.job.mariadbrestore.backoffLimit | default 0 | int }}
  activeDeadlineSeconds: {{ $.Values.job.mariadbrestore.activeDeadlineSeconds | default 3600 | int }}
  ttlSecondsAfterFinished: {{ $.Values.job.mariadbrestore.ttlSecondsAfterFinished | default 43200 | int }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        release: {{ $.Release.Name }}
      annotations:
        checksum/entrypoint.sh: {{ include (print $.Template.BasePath "/configmap-mariadb-entrypoint-job-restore.sh.yaml") $ | sha256sum }}
        checksum/common-functions-extended.sh: {{ include (print $.Template.BasePath "/configmap-mariadb-common-functions-extended.sh.yaml") $ | sha256sum }}
    spec:
      restartPolicy: {{ $.Values.job.mariadbrestore.jobRestartPolicy | default "Never" | quote }}
      serviceAccount: {{ $.Release.Name }}
      securityContext:
        fsGroup:  {{ $.Values.groupId.application | default 101 | int }}
      imagePullSecrets:
      - name: {{ $.Release.Name }}-{{$.Values.image.application.pullSecret}}
      containers:
      - name: restore
        image: "{{ $.Values.image.application.registry }}/{{ $.Values.image.application.project }}/{{ $.Values.image.application.applicationname }}:{{ $.Values.image.application.applicationversion }}-{{ $.Values.image.application.imageversion }}"
        imagePullPolicy: {{ $.Values.image.application.pullPolicy | default "IfNotPresent" | quote }}
        securityContext:
          runAsUser:  {{ $.Values.userId.application | default 101 | int }}
          runAsGroup: {{ $.Values.groupId.application | default 101 | int }}
        {{- if and ($.Values.command) (hasKey $.Values.command "jobrestore") }}
        command:
{{ $.Values.command.jobrestore | toYaml | indent 8 }}
        {{- else }}
        command:
          - "sh"
          - "-c"
          - "/opt/mariadb/bin/entrypoint-job-restore.sh"
        {{- end }}
        env:
        - name: OS_AUTH_URL
          value: {{ required "Values.mariadb.galera.backup.openstack.authurl is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.authurl | quote }}
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_REGION_NAME
          value: {{ required "Values.mariadb.galera.backup.openstack.region is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.region | quote }}
        - name: OS_PROJECT_NAME
          value: {{ required "Values.mariadb.galera.backup.openstack.projectname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.projectname | quote }}
        - name: OS_PROJECT_DOMAIN_NAME
          value: {{ required "Values.mariadb.galera.backup.openstack.tenantname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.tenantname | quote }}
        - name: OS_USER_DOMAIN_NAME
          value: {{ required "Values.mariadb.galera.backup.openstack.tenantname is missing, but required for the Openstack Swift authentication." $.Values.mariadb.galera.backup.openstack.tenantname | quote }}
        - name: DB_HOST
          value: "{{ (include "nodeNamePrefix" (dict "global" $ "component" "application")) }}-0.database.svc.cluster.local"
        - name: MYSQL_PORT
          value: {{ (required ".services.application.frontend.ports.mysql.targetPort missing" $.Values.services.application.frontend.ports.mysql.targetPort) | quote }}
        - name: RESTIC_REPOSITORY
          value: {{ (printf "swift:%s:/" (required "Values.mariadb.galera.backup.openstack.container is missing, but required for restic to access the repository." $.Values.mariadb.galera.backup.openstack.container)) | quote }}
        - name: RESTIC_PROGRESS_FPS
          value: {{ $.Values.mariadb.galera.restore.restic.progressFps | default "0.01666" | quote }}
        - name: RESTIC_CACHE_DIR
          value: "/opt/mariadb/run/"
        - name: TMPDIR
          value: "/opt/mariadb/tmp/"
        - name: RESTORE_TIMESTAMP
          value: {{ $.Values.mariadb.galera.restore.beforeTimestamp | default "false" | quote }}
        - name: RESTORE_SNAPSHOT_ID
          value: {{ $.Values.mariadb.galera.restore.restic.snapshotId | default "false" | quote }}
        {{- range $envKey, $envValue := $.Values.env }}
          {{- if (has "jobrestore" $envValue.containerType) }}
        - name: {{ $envKey }}
            {{- if $envValue.value }}
          value: {{ $envValue.value | quote }}
            {{- end }}
            {{- if $envValue.secretName }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-{{ $envValue.secretName }}
              key: {{ $envValue.secretKey }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ $.Values.resourceLimits.cpu.jobrestore | default 0.5 }}
          limits:
            memory: {{ $.Values.resourceLimits.memory.jobrestore | default "128Mi" | quote }}
        volumeMounts:
        - name: mariadbrestore-job-entrypoint-sh
          mountPath: /opt/mariadb/bin/entrypoint-job-restore.sh
          subPath: entrypoint-job-restore.sh
          readOnly: true
        - name: mariadb-common-functions-extended-sh
          mountPath: /opt/mariadb/bin/common-functions-extended.sh
          subPath: common-functions-extended.sh
          readOnly: true
      volumes:
      {{- range $volumeMountsKey, $volumeMountsValue := $.Values.volumeMounts.application }}
        {{- if $volumeMountsValue.type }}
          {{- if ne $volumeMountsValue.type "persistentVolume" }}
      - name: {{ $volumeMountsKey }}
            {{- if eq $volumeMountsValue.type "secret"}}
        {{ $volumeMountsValue.type }}:
          secretName: {{ $.Release.Name }}-{{ $volumeMountsKey }}
            {{- else if eq $volumeMountsValue.type "hostPath" }}
        {{ $volumeMountsValue.type }}:
          path: {{ $volumeMountsValue.hostPath }}
            {{- else }}
          name: {{ $volumeMountsKey }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      - name: mariadbrestore-job-entrypoint-sh
        configMap:
          name: mariadbrestore-job-entrypoint-sh
          defaultMode: 0750
      - name: mariadb-common-functions-extended-sh
        configMap:
          name: mariadb-common-functions-extended-sh
          defaultMode: 0755
{{- end }}