{{- if and (hasKey $.Values.mariadb "autostart") (not $.Values.mariadb.autostart) }}
{{- else if and ($.Values.command) (hasKey $.Values.command "application") }}
{{- else if or (and (hasKey $.Values.mariadb.galera.restore "restic") ($.Values.mariadb.galera.restore.restic.enabled)) (and (hasKey $.Values.mariadb.galera.restore "kopia") ($.Values.mariadb.galera.restore.kopia.enabled)) }}
{{- else if and (hasKey $.Values.mariadb "wipeDataAndLog") ($.Values.mariadb.wipeDataAndLog) }}
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ (include "nodeNamePrefix" (dict "global" $ "component" "application")) }}-cfg-{{ randAlphaNum 8 | lower }}
  labels:
    app: {{ $.Release.Name }}
    release: {{ $.Release.Name }}
spec:
  backoffLimit: {{ $.Values.job.mariadbconfig.backoffLimit | default 6 | int }}
  activeDeadlineSeconds: {{ $.Values.job.mariadbconfig.activeDeadlineSeconds | default 300 | int }}
  ttlSecondsAfterFinished: {{ $.Values.job.mariadbconfig.ttlSecondsAfterFinished | default 120 | int }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        release: {{ $.Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap-mariadb-job.yaml") $ | sha256sum }}
    spec:
      restartPolicy: {{ $.Values.job.mariadbconfig.jobRestartPolicy | default "OnFailure" | quote }}
      serviceAccount: {{ include "commonPrefix" $ }}{{ $.Release.Name }}
      securityContext:
        fsGroup:  {{ $.Values.groupId.application | default 101 | int }}
      imagePullSecrets:
      - name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-{{$.Values.image.application.pullSecret}}
      containers:
      - name: cfg
        image: "{{ $.Values.image.application.registry }}/{{ $.Values.image.application.project }}/{{ $.Values.image.application.applicationname }}:{{ $.Values.image.application.applicationversion }}-{{ $.Values.image.application.imageversion }}"
        imagePullPolicy: {{ $.Values.image.application.pullPolicy | default "IfNotPresent" | quote }}
        securityContext:
          runAsUser:  {{ $.Values.userId.application | default 101 | int }}
          runAsGroup: {{ $.Values.groupId.application | default 101 | int }}
        {{- if and ($.Values.command) (hasKey $.Values.command "jobconfig") }}
        command:
{{ $.Values.command.jobconfig | toYaml | indent 8 }}
        {{- else }}
        command:
          - "sh"
          - "-c"
          - "/opt/mariadb/bin/entrypoint-job-config.sh"
        {{- end }}
        env:
        - name: MYSQL_PORT
          value: {{ (required ".services.application.frontend.ports.mysql.targetPort missing" $.Values.services.application.frontend.ports.mysql.targetPort) | quote }}
        {{- if not (hasKey $.Values.env "MARIADB_MONITORING_CONNECTION_LIMIT") }}
        - name: MARIADB_MONITORING_CONNECTION_LIMIT
          value: 3
        {{- end }}
        {{- range $envKey, $envValue := $.Values.env }}
          {{- if (has "jobconfig" $envValue.containerType) }}
        - name: {{ $envKey }}
            {{- if $envValue.value }}
          value: {{ $envValue.value | quote }}
            {{- end }}
            {{- if $envValue.secretName }}
          valueFrom:
            secretKeyRef:
              name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-{{ $envValue.secretName }}
              key: {{ $envValue.secretKey }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ $.Values.resourceLimits.cpu.jobconfig | default 0.25 }}
          limits:
            memory: {{ $.Values.resourceLimits.memory.jobconfig | default "32Mi" | quote }}
        volumeMounts:
        - name: {{ include "commonPrefix" $ }}mariadb-config-job-entrypoint-sh
          mountPath: /opt/mariadb/bin/entrypoint-job-config.sh
          subPath: entrypoint-job-config.sh
          readOnly: true
        - name: {{ include "commonPrefix" $ }}mariadb-common-functions-extended-sh
          mountPath: /opt/mariadb/bin/common-functions-extended.sh
          subPath: common-functions-extended.sh
          readOnly: true
      volumes:
      {{- range $volumeMountsKey, $volumeMountsValue := $.Values.volumeMounts.application }}
        {{- if $volumeMountsValue.type }}
          {{- if ne $volumeMountsValue.type "persistentVolume" }}
      - name: {{ include "commonPrefix" $ }}{{ $volumeMountsKey }}
            {{- if eq $volumeMountsValue.type "secret"}}
        {{ $volumeMountsValue.type }}:
          secretName: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-{{ $volumeMountsKey }}
            {{- else if eq $volumeMountsValue.type "hostPath" }}
        {{ $volumeMountsValue.type }}:
          path: {{ $volumeMountsValue.hostPath }}
            {{- else }}
          name: {{ include "commonPrefix" $ }}{{ $volumeMountsKey }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      - name: {{ include "commonPrefix" $ }}mariadb-config-job-entrypoint-sh
        configMap:
          name: {{ include "commonPrefix" $ }}mariadb-config-job-entrypoint-sh
          defaultMode: 0750
      - name: {{ include "commonPrefix" $ }}mariadb-common-functions-extended-sh
        configMap:
          name: {{ include "commonPrefix" $ }}mariadb-common-functions-extended-sh
          defaultMode: 0755
{{- end }}