apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Values.namePrefix | default "mariadb-g" }}-cfg-{{ uuidv4 | lower }}
  labels:
    app: {{ $.Release.Name }}
    release: {{ $.Release.Name }}
spec:
  backoffLimit: {{ $.Values.backoffLimit | default 6 }}
  activeDeadlineSeconds: {{ $.Values.activeDeadlineSeconds | default 300 }}
  ttlSecondsAfterFinished: {{ $.Values.ttlSecondsAfterFinished | default 120 }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        release: {{ $.Release.Name }}
      annotations:
        checksum/entrypoint.sh: {{ include (print $.Template.BasePath "/configmap-job-entrypoint.sh.yaml") $ | sha256sum }}
        checksum/common-functions.sh: {{ include (print $.Template.BasePath "/configmap-common-functions.sh.yaml") $ | sha256sum }}
    spec:
      restartPolicy: {{ $.Values.restartPolicy | default "OnFailure" | quote }}
      serviceAccount: {{ $.Release.Name }}
      securityContext:
        fsGroup:  {{ $.Values.groupId.application }}
      imagePullSecrets:
      - name: {{ $.Release.Name }}-{{$.Values.image.application.pullSecret}}
      containers:
      - name: cfg
        image: "{{ $.Values.image.application.registry }}/{{ $.Values.image.application.project }}/{{ $.Values.image.application.applicationname }}:{{ $.Values.image.application.applicationversion }}-{{ $.Values.image.application.imageversion }}"
        imagePullPolicy: {{ $.Values.image.application.pullPolicy | default "IfNotPresent" | quote }}
        securityContext:
          runAsUser:  {{ $.Values.userId.application }}
          runAsGroup: {{ $.Values.groupId.application }}
        {{- if and ($.Values.command) (hasKey $.Values.command "job") }}
        command:
{{ $.Values.command.job | toYaml | indent 8 }}
        {{- else }}
        command:
          - "sh"
          - "-c"
          - "/opt/mariadb/bin/entrypoint-job.sh"
        {{- end }}
        env:
        - name: MYSQL_PORT
        {{- range $servicesKey, $servicesValue := $.Values.services }}
          {{- if eq $servicesValue.name "frontend"}}
            {{- range $portsKey, $portsValue := $servicesValue.ports }}
              {{- if eq $portsValue.name "mysql"}}
          value: "{{ $portsValue.targetPort }}"
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if not (hasKey $.Values.env "MARIADB_MONITORING_CONNECTION_LIMIT") }}
        - name: MARIADB_MONITORING_CONNECTION_LIMIT
          value: 3
        {{- end }}
        {{- range $envKey, $envValue := $.Values.env }}
          {{- if (has "job" $envValue.containerType) }}
        - name: {{ $envKey }}
            {{- if $envValue.value }}
          value: {{ $envValue.value | quote }}
            {{- end }}
            {{- if $envValue.secretName }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-{{ $envValue.secretName }}
              key: {{ $envValue.secretKey }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ $.Values.resourceLimits.cpu.job | default 0.25 }}
          limits:
            memory: {{ $.Values.resourceLimits.memory.job | default "32Mi" | quote }}
        volumeMounts:
        - name: job-entrypoint-sh
          mountPath: /opt/mariadb/bin/entrypoint-job.sh
          subPath: entrypoint-job.sh
          readOnly: true
        - name: common-functions-sh
          mountPath: /opt/mariadb/bin/common-functions.sh
          subPath: common-functions.sh
          readOnly: true
      volumes:
      {{- range $volumeMountsKey, $volumeMountsValue := $.Values.volumeMounts }}
        {{- if $volumeMountsValue.type }}
          {{- if ne $volumeMountsValue.type "persistentVolume" }}
      - name: {{ $volumeMountsValue.name }}
            {{- if eq $volumeMountsValue.type "secret"}}
        {{ $volumeMountsValue.type }}:
          secretName: {{ $.Release.Name }}-{{ $volumeMountsValue.name }}
            {{- else if eq $volumeMountsValue.type "hostPath" }}
        {{ $volumeMountsValue.type }}:
          path: {{ $volumeMountsValue.hostPath }}
            {{- else }}
          name: {{ $volumeMountsValue.name }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      - name: job-entrypoint-sh
        configMap:
          name: job-entrypoint-sh
          defaultMode: 0750
      - name: common-functions-sh
        configMap:
          name: common-functions-sh
          defaultMode: 0755
