---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Release.Name }}
spec:
  maxUnavailable: {{ $.Values.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
