apiVersion: v1
type:
kind: List
metadata:
  name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-secrets
  namespace: {{ $.Release.Namespace }}
items:
{{- range $userKey, $userValue := $.Values.mariadb.users }}
  {{- if $userValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $userKey "credential" $userValue "suffix" "mariadb" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.proxy.users }}
  {{- if $userValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $userKey "credential" $userValue "suffix" "proxy" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.mariadb.galera.backup.restic.users }}
  {{- if $userValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $userKey "credential" $userValue "suffix" "restic" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.mariadb.galera.backup.kopia.users }}
  {{- if $userValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $userKey "credential" $userValue "suffix" "kopia" "kind" "Secret") }}
  {{- end }}
{{- end }}
