apiVersion: v1
type:
kind: List
metadata:
  name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-secrets
  namespace: {{ $.Release.Namespace }}
items:
{{- range $credentialKey, $credentialValue := $.Values.mariadb.users }}
  {{- if $credentialValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $credentialKey "credential" $credentialValue "suffix" "mariadb" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $credentialKey, $credentialValue := $.Values.proxy.users }}
  {{- if $credentialValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $credentialKey "credential" $credentialValue "suffix" "proxysql" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $credentialKey, $credentialValue := $.Values.mariadb.galera.backup.restic.users }}
  {{- if $credentialValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $credentialKey "credential" $credentialValue "suffix" "restic" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $credentialKey, $credentialValue := $.Values.mariadb.galera.backup.kopia.users }}
  {{- if $credentialValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $credentialKey "credential" $credentialValue "suffix" "kopia" "kind" "Secret") }}
  {{- end }}
{{- end }}
{{- range $credentialKey, $credentialValue := $.Values.image.pullSecrets }}
  {{- if $credentialValue.enabled }}
    {{- include "generateSecret" (dict "global" $ "name" $credentialKey "credential" $credentialValue "kind" "Dockerconfigjson") }}
  {{- end }}
{{- end }}
