apiVersion: v1
type:
kind: List
metadata:
  name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-secrets
  namespace: {{ $.Release.Namespace }}
items:
{{- range $userKey, $userValue := $.Values.mariadb.users }}
  {{- if $userValue.enabled }}
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-mariadb-{{ $userKey }}
  data:
    {{- if $userValue.username }}
    username: {{ $userValue.username | b64enc }}
    {{- end }}
    password: {{ $userValue.password | b64enc }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.proxy.users }}
  {{- if $userValue.enabled }}
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-proxysql-{{ $userKey }}
  data:
    {{- if $userValue.username }}
    username: {{ $userValue.username | b64enc }}
    {{- end }}
    password: {{ $userValue.password | b64enc }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.mariadb.galera.backup.restic.users }}
  {{- if $userValue.enabled }}
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-restic-{{ $userKey }}
  data:
    {{- if $userValue.username }}
    username: {{ $userValue.username | b64enc }}
    {{- end }}
    password: {{ $userValue.password | b64enc }}
  {{- end }}
{{- end }}
{{- range $userKey, $userValue := $.Values.mariadb.galera.backup.kopia.users }}
  {{- if $userValue.enabled }}
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    namespace: {{ $.Release.Namespace }}
    name: {{ include "commonPrefix" $ }}{{ $.Release.Name }}-kopia-{{ $userKey }}
  data:
    {{- if $userValue.username }}
    username: {{ $userValue.username | b64enc }}
    {{- end }}
    password: {{ $userValue.password | b64enc }}
  {{- end }}
{{- end }}
