{{/* application services */}}
{{- range $serviceKey, $serviceValue := $.Values.services.application }}
  {{- $service := dict "key" $serviceKey "value" $serviceValue }}
  {{- if eq $serviceValue.name "backend"}}
    {{- range $replicaNumber, $err := until ($.Values.replicas.application|int) }}
      {{/* per pod service to generate per pod hostnames */}}
      {{ include "networkService" (dict "global" $ "service" $service "component" "application" "replica" ($replicaNumber|toString)) }}
    {{- end }}
    {{/* backend service for all pods */}}
    {{ include "networkService" (dict "global" $ "service" $service "component" "application" "replica" "notused") }}
  {{- else if and (eq $serviceValue.name "frontend") (not $.Values.proxy.enabled) }}
    {{/* other frontend services for all pods */}}
    {{ include "networkService" (dict "global" $ "service" $service "component" "application" "replica" "notused") }}
  {{- end }}
{{- end }}
{{/* proxy services */}}
{{- if $.Values.proxy.enabled }}
  {{- range $serviceKey, $serviceValue := $.Values.services.proxy }}
    {{- $service := dict "key" $serviceKey "value" $serviceValue }}
    {{- if eq $serviceValue.name "backend"}}
      {{- range $replicaNumber, $err := until ($.Values.replicas.application|int) }}
        {{/* per pod service to generate per pod hostnames */}}
        {{ include "networkService" (dict "global" $ "service" $service "component" "proxy" "replica" ($replicaNumber|toString)) }}
      {{- end }}
      {{ include "networkService" (dict "global" $ "service" $service "component" "proxy" "replica" "notused") }}
    {{- else if and (eq $serviceValue.name "frontend") $.Values.proxy.enabled }}
      {{ include "networkService" (dict "global" $ "service" $service "component" "proxy" "replica" "notused") }}
    {{- end }}
  {{- end }}
{{- end }}