{{/* MariaDB services */}}
  {{/* backend */}}
    {{/* per pod service to generate per pod hostnames */}}
    {{- range $replicaNumber, $err := until ($.Values.replicas.application|int) }}
      {{ include "networkService" (dict "global" $ "type" "backend" "service" (required ".services.application.backend missing" $.Values.services.application.backend) "component" "application" "replica" ($replicaNumber | toString)) }}
    {{- end }}
    {{/* shared service for all pods */}}
    {{ include "networkService" (dict "global" $ "type" "backend" "service" (required ".services.application.backend missing" $.Values.services.application.backend) "component" "application" "replica" "notused") }}
  {{/* frontend */}}
  {{/* other frontend services for all pods */}}
    {{- if not $.Values.proxy.enabled }}
      {{ include "networkService" (dict "global" $ "type" "frontend" "service" (required ".services.application.frontend missing" $.Values.services.application.frontend) "component" "application" "replica" "notused") }}
      {{ include "networkService" (dict "global" $ "type" "frontend" "service" (required ".services.application.frontend missing" $.Values.services.application.frontend) "component" "application-direct" "replica" "notused") }}
    {{- else if $.Values.proxy.enabled }}
      {{ include "networkService" (dict "global" $ "type" "frontend" "service" (required ".services.application.frontend missing" $.Values.services.application.frontend) "component" "application-direct" "replica" "notused") }}
    {{- end }}

{{/* ProxySQL services */}}
  {{/* backend */}}
    {{/* per pod service to generate per pod hostnames */}}
    {{- range $replicaNumber, $err := until ($.Values.replicas.proxy|int) }}
      {{ include "networkService" (dict "global" $ "type" "backend" "service" (required ".services.proxy.backend missing" $.Values.services.proxy.backend) "component" "proxy" "replica" ($replicaNumber | toString)) }}
    {{- end }}
    {{/* shared service for all pods */}}
    {{ include "networkService" (dict "global" $ "type" "backend" "service" (required ".services.proxy.backend missing" $.Values.services.proxy.backend) "component" "proxy" "replica" "notused") }}
  {{/* frontend */}}
  {{/* other frontend services for all pods */}}
    {{- if $.Values.proxy.enabled }}
      {{ include "networkService" (dict "global" $ "type" "frontend" "service" (required ".services.proxy.frontend missing" $.Values.services.proxy.frontend) "component" "proxy" "replica" "notused") }}
    {{- end }}

{{/* Kopia services */}}
  {{/* frontend */}}
    {{- if and (and (hasKey $.Values.mariadb.galera "backup") ($.Values.mariadb.galera.backup.enabled)) (and (hasKey $.Values.mariadb.galera.backup "kopia") ($.Values.mariadb.galera.backup.kopia.enabled)) }}
      {{ include "networkService" (dict "global" $ "type" "frontend" "service" (required ".services.kopiaserver.frontend missing" $.Values.services.kopiaserver.frontend) "component" "kopiaserver" "replica" "notused") }}
    {{- end }}
