apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-harvest.fullname" . }}
  labels:
    {{- include "netapp-harvest.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: {{ required ".Values.global.netapp_exporter_user" .Values.global.netapp_exporter_user | b64enc | quote }}
  netappPassword: {{ required ".Values.global.netapp_exporter_password" .Values.global.netapp_exporter_password | b64enc | quote }}
