global:
  region: test
  tld: test.corp
  imageRegistry: testRepo
  image_namespace: testNamespace
  registryAlternateRegion: test-1

unbound:
  name: "testunbound"
  image_unbound: sapcc/unbound
  image_unbound_exporter: sapcc/unbound_exporter
  image_unbound_tag: latest 
  image_unbound_exporter_tag: latest 
  image_pullPolicy: IfNotPresent
  port_unbound_exporter: 9107
  interface: 0.0.0.0
  failure_domain_zone: a
  externalIP: 127.0.0.1
  unbound_control_key: "test"
  unbound_control_pem: "test"
  unbound_server_key: "test"
  unbound_server_pem: "test"

alerts:
  prometheus: openstack
