apiVersion: v2
name: hermes-query-exporter
version: 0.0.1
description: Elasticsearch prometheus query exporter for Hermes
maintainers:
  - name: Olaf Heydorn
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
