owner-info:
  support-group: observability
  maintainers:
    - "Olaf Heydorn"
  helm-chart-url: "https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/hermes-query-exporter"

enabled: true
version: "20220317091500"
listen_port: 9206
hostname: elasticsearch
protocol: http
port: 9200
log_level: "ERROR"
alerts:
  enabled: false
  prometheus: infra-collector
