apiVersion: v2
name: ucs-exporter
version: 0.0.2
description: Exporter for UCSM/UCSC Server
maintainers:
  - name: Bernd Kuespert
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
