{{ if .Values.logstash.audit -}}
kind: Secret
apiVersion: v1
metadata:
  name: logstash-secret
  namespace: hermes
  labels:
    system: openstack
    service: audit
data:
  # If a region is not configured, default value
  METIS_PASSWORD: {{ .Values.global.metis.password | default "default" | b64enc }}
{{- end}}
