# Default values for locust.
# This is a YAML-formatted file.
locustCmd: "locust -f /data/src/openstack_performance/openstack.py OpenstackUser"
pip_packages:
  - keystoneauth1
  - urllib3

command:
  - sh
  - /config/docker-entrypoint.sh
image:
  repository: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/locustio/locust
  pullPolicy: Always
