{{- if .Values.manila_nanny.enabled }}
{{- if .Values.manila_nanny.quota_sync.enabled}}
kind: Service
apiVersion: v1
metadata:
  name: manila-nanny-quota-sync
  namespace: monsoon3
  labels:
    system: openstack
    service: manila-nanny
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
    nanny: quota-sync
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9456"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: manila-nanny
  ports:
    - name: metrics
      port: 9456
{{- end }}
{{- if .Values.manila_nanny.share_sync.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: manila-nanny-share-sync
  namespace: monsoon3
  labels:
    system: openstack
    service: manila-nanny
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
    nanny: share-sync
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.manila_nanny.share_sync.prometheus_port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: manila-nanny
  ports:
    - name: metrics
      port: {{ .Values.manila_nanny.share_sync.prometheus_port }}
{{- end }}
{{- if .Values.manila_nanny.share_server.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: manila-nanny-share-server
  namespace: monsoon3
  labels:
    system: openstack
    service: manila-nanny
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
    nanny: share-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.manila_nanny.share_server.prometheus_port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: manila-nanny
  ports:
    - name: metrics
      port: {{ .Values.manila_nanny.share_server.prometheus_port }}
{{- end }}
{{- if .Values.manila_nanny.snapshot.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: manila-nanny-snapshot
  namespace: monsoon3
  labels:
    system: openstack
    service: manila-nanny
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
    nanny: snapshot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.manila_nanny.snapshot.prometheus_port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: manila-nanny
  ports:
    - name: metrics
      port: {{ .Values.manila_nanny.snapshot.prometheus_port }}
{{- end }}
{{- if .Values.manila_nanny.snapshot_missing.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: manila-nanny-snapshot-missing
  namespace: monsoon3
  labels:
    system: openstack
    service: manila-nanny
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
    nanny: snapshot-missing
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.manila_nanny.snapshot_missing.prometheus_port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: manila-nanny
  ports:
    - name: metrics
      port: {{ .Values.manila_nanny.snapshot_missing.prometheus_port }}
{{- end }}
{{- end }}
