{{- if .Values.manila_nanny.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-netapp-filers
  labels:
    system: openstack
    service: manila-nanny
data:
  netapp-filers.yaml: |
    filers:
      {{- range .Values.global.netapp.filers }}
      - host: {{ .host }}
        name: {{ .name }}
      {{- end}}
{{- end }}
