apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vpa-butler
  name: vpa-butler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-butler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-butler
    spec:
      containers:
      - image: {{ required ".Values.image.repository missing" .Values.image.repository }}:{{ required ".Chart.AppVersion missing" .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        name: vpa-butler
        args:
          - --default-vpa-update-mode={{ required ".Values.updateMode missing" .Values.updateMode | quote }}
          - --capacity-percent={{ required ".Values.capacityPercent missing" .Values.capacityPercent }}
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
      serviceAccountName: vpa-butler
