apiVersion: v2
name: vertical-pod-autoscaler
description: A Helm chart for the vertical pod autoscaler.
type: application
# The version of this Helm chart.
version: 3.0.0
# The version of the VPA.
# This is also used as the image tag.
appVersion: 0.13.0
