# TODO: Once Clair is abandoned, remove this constraint and update the main
# GkVulnerableImages constraint to refer to the Trivy vuln status header.

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkVulnerableImages
metadata:
  name: vulnerableimages-trivy
  annotations:
    {{- include "sources" (tuple "vulnerable-images" "vulnerable-images-trivy") | indent 4 }}
  labels:
    on-prod-ui: 'false' # NOTE: feature preview
spec:
  enforcementAction: dryrun # change to "deny" to enforce
  match: {{ include "match_pods_only" . | indent 4 }}
  parameters:
    doopImageCheckerURL: {{ quote .Values.doop_image_checker_url }}
    vulnStatusHeader: X-Keppel-Trivy-Vulnerability-Status
