apiVersion: v2
name: pulsar
description: Tool to acknowledge pagerduty incidents in Slack
type: application
version: 1.2.4
appVersion: 1.0.4

dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
