{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-query-exporter
  namespace: hermes
  labels:
    component: hermes-query-exporter
spec:
  selector:
    matchLabels:
      component: hermes-query-exporter
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: hermes-query-exporter
      annotations:
        checksum/configmap.yaml: {{ include  (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: hermes-query-exporter
          configMap:
            name: hermes-query-exporter
      containers:
        - name: hermes-query-exporter
          image: {{.Values.global.registry}}/prometheus-es-exporter:{{ .Values.version }}
          imagePullPolicy: Always
          command: [ "prometheus-es-exporter", "-p", "{{.Values.listen_port}}", "--config-dir", "/hermes-query-exporter/", "--cluster-health-disable", "--indices-stats-disable", "--basic-user", "{{ .Values.global.prom_user }}", "--basic-password", "{{ .Values.global.prom_password }}", "-e", "{{.Values.protocol}}://{{.Values.hostname}}:{{.Values.port}}", "--log-level", "{{.Values.log_level}}", "--nodes-stats-disable" ]
          ports:
            - name: metrics
              containerPort: {{ .Values.listen_port }}
          volumeMounts:
            - mountPath: /hermes-query-exporter
              name: hermes-query-exporter
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
{{- end }}
