apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-auto-failover.monitor.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ include "postgresql-auto-failover.monitor.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "{{ .Values.postgresDatabase }}"
    type: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: {{ include "postgresql-auto-failover.fullname" . }}
    app.kubernetes.io/component: monitor
