kind: Service
apiVersion: v1

metadata:
  name: keppel-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/targets: "openstack"

spec:
  selector:
    name: keppel-api
  ports:
    - name: metrics # this specific name is required for Prometheus scraping
      port: 80
      protocol: TCP
