username: ${SYSBENCH_USERNAME}
hostnames:
  - "%"
  - "::1"
  - "localhost"
password: ${SYSBENCH_PASSWORD}
authplugin: mysql_native_password
adminoption: false
maxconnections: 0
defaultrole: contentfullaccess
proxysql:
  fastforward: false