{{ if .Values.source }}
kind: Service
apiVersion: v1
metadata:
  name: statsd
  labels:
    component: backup-replication
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: statsd-exporter
  ports:
    - name: statsd
      port: 9125
      protocol: UDP
    - name: metrics
      port: 9102
      protocol: TCP
{{ end }}
