apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: gkimagesfromnonkeppel
spec:
  crd:
    spec:
      names:
        kind: GkImagesFromNonKeppel

  targets:
    - target: admission.k8s.gatekeeper.sh
      libs:
        - |
          {{ .Files.Get "lib/add-support-labels.rego" | nindent 10 }}
        - |
          {{ .Files.Get "lib/traversal.rego" | nindent 10 }}
      rego: |
        package imagesfromnonkeppel
        import data.lib.add_support_labels
        import data.lib.traversal

        iro := input.review.object
        containers := traversal.find_container_specs(iro)

        violation[{"msg": add_support_labels.from_k8s_object(iro, msg)}] {
          container := containers[_]
          image := container.image

          not regex.match("^keppel\\.[^/.]*\\.cloud.sap/", image)
          msg := sprintf("container %q uses an image that is not from a Keppel registry: %s", [container.name, image])
        }
