# You can override subchart values here, e.g. concurrency

# Required!
# Please specify a run pattern. They are different for tempest-plugins. Sometimes its $PLUGIN.api and sometimes $PLUGIN.tests.api - Check the $PLUGIN git repo for the pattern.
run_pattern: manila_tempest_tests.tests.api
tempest_branch: ccloud-python3

# Optional
# Concurrency default is 1
#concurrency: 8
owner-info:
  helm-chart-url: 'https://github.com/sapcc/helm-charts/tree/master/openstack/tempest/manila-tempest'
  maintainers:
    - Mikhail Samoylov
    - Dmitry Galkin
  # "support-group" is required for routing alerts/tickets regarding this
  # deployment to the right support group
  support-group: ''
  # "service" is optional and allows sorting of alerts/tickets within the realm
  # of a single support group
  service: ''