apiVersion: v2
name: elastiflow-query-exporter
version: 1.0.1
description: Elasticsearch prometheus query exporter for Elastiflow
maintainers:
  - name: Ivo Gosemann
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
