global:
  keystoneNamespace: keystone
  region: xx-yy-1
  tld: example.org
  dockerHubMirror: registry.example.com/dockerhub
  quayIoMirror: registry.example.com/quayio

limes:
  image_tag: '19700101000000'

  clusters:
    ccloud:

  passwords:
    ccloud:
      os_password: abc
      rabbitmq_password: def

postgresql:
  postgresPassword: abcdef
pgmetrics:
  db_password: abcdef
