global:
  region: earth
  os_auth_url: my_keystone_url
  domain_seeds:
    skip_hcm_domain: false
prometheus-server:
  name: my_prom_name
maia:
  endpoint_host_public: my_maia_endpoint
  docker_repo: my_docker_repository
  service_user:
    password: topSecret
