{{- if .Values.multicloudtest.enabled }}
{{ $mct := $.Values.multicloudtest }}
{{- range $.Values.multicloudtest.clouds }}
---
apiVersion: v1
kind: Secret
data:
  creds.json: {{ .creds_json | toJson | b64enc }}
  private_key: {{ $.Values.multicloudtest.ssh.private_key.value | b64enc }}
  public_key.pub: {{ $.Values.multicloudtest.ssh.public_key.value | b64enc }}
metadata:
  name: multicloudtest-creds-{{ .name }}
  namespace: cc3test
{{- end }}
{{- end }}
