# Default values for netapp-cap-exporter.
enabled: true
fullname: netapp-capacity-exporter

prometheus:
  scrape: true
  port: 9108

apps:
  cinder:
    enabled: false
    component: "cinder"
    netappsd:
      query: bb
  baremetal:
    enabled: false
    component: "bare-metal"
    netappsd:
      query: bm
  controlplane:
    enabled: false
    component: "control-plane"
    netappsd:
      query: cp
  manila:
    enabled: false
    component: "manila"
    resources:
      requests:
        memory: 400Mi
        cpu: 100m

exporter:
  image:
    repository: netapp-api-exporter
    tag: 20221201213801-master-d3aa6f4
  rsources:
    requests:
      memory: 200Mi
      cpu: 100m

netappsd:
  image:
    repository: netappsd
    tag: master-ad6b560-20221007205120
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
