{{- if and .Values.global.linkerdEnabled .Values.annotateNamespace }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotate-namespace-for-linkerd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: annotate-namespace-for-linkerd
rules:
- apiGroups: [ "" ]
  resources: [ namespaces ]
  resourceNames: [ {{ .Release.Namespace }} ]
  verbs: [ get, patch ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: annotate-namespace-for-linkerd
subjects:
  - kind: ServiceAccount
    name: annotate-namespace-for-linkerd
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: annotate-namespace-for-linkerd
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-namespace-for-linkerd
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        name: annotate-namespace-for-linkerd
    spec:
      restartPolicy: Never
      serviceAccountName: annotate-namespace-for-linkerd
      containers:
      - name: annotate
        image: "{{ .Values.global.dockerHubMirror | required ".Values.global.dockerHubMirror not found" }}/bitnami/kubectl:latest"
        command:
          - kubectl
          - annotate
          - ns
          - {{ .Release.Namespace }}
          - linkerd.io/inject=enabled

{{- end }}
