configs:
  - name: sb_oltp_ro
    enabled: true
    description: "for the sysbench oltp readonly benchmark"
    type: database
    file: "sb_oltp_ro.yaml"
  - name: contentfullaccess
    enabled: true
    description: "full access to all databases without admin access to the server process itself"
    type: role
    file: "contentfullaccess.yaml"
  - name: root
    enabled: false
    description: "root access to the database server process"
    type: role
    file: "root.yaml"
  - name: sstbackup
    enabled: true
    description: "sst backup method https://mariadb.com/kb/en/mariabackup-sst-method/#authentication-and-privileges"
    type: role
    file: "sstbackup.yaml"
  - name: replication
    enabled: true
    description: "role to allow master/slave replication https://mariadb.com/kb/en/configuring-mariadb-replication-between-two-mariadb-galera-clusters/"
    type: role
    file: "replication.yaml"
  - name: openstack_citest
    enabled: true
    description: "user for oslo.db unit tests https://docs.openstack.org/oslo.db/latest/contributor/index.html#how-to-run-unit-tests"
    type: user
    file: "openstack_citest.yaml"
  - name: sysbench
    enabled: true
    description: "user for sysbench benchmarking https://docs.openstack.org/developer/performance-docs/test_plans/db/plan.html"
    type: user
    file: "sysbench.yaml"
  - name: mariabackup
    enabled: true
    description: "user for sst with mariabackup and garbd based backups"
    type: user
    file: "mariabackup.yaml"
  - name: replica
    enabled: true
    description: "user for replica to primary connections (master/slave replication)"
    type: user
    file: "replica.yaml"
