configs:
  - name: contentfullaccess
    enabled: true
    description: "full access to all databases without admin access to the server process itself"
    type: role
    file: "contentfullaccess.yaml"
  - name: root
    enabled: false
    description: "root access to the database server process"
    type: role
    file: "root.yaml"
  - name: openstack_citest
    enabled: true
    description: "user for oslo.db unit tests https://docs.openstack.org/oslo.db/latest/contributor/index.html#how-to-run-unit-tests"
    type: user
    file: "openstack_citest.yaml"
