apiVersion: v1
kind: ConfigMap
metadata:
  name: codi-db-maintain
  labels:
    system: codimd
    type: configuration
    component: database

data:
  db-maintain.sql: |
    \set ON_ERROR_STOP off {{/* We even expect the CREATE to fail, except for the first run */}}
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
    CREATE ROLE {{ .Values.codimd.codimd.database.username }} WITH ENCRYPTED PASSWORD '{{ .Values.codimd.codimd.database.password }}' LOGIN;

    CREATE DATABASE {{ .Values.codimd.codimd.database.databaseName }} WITH OWNER {{ .Values.codimd.codimd.database.username }};
    \set ON_ERROR_STOP on

    ALTER ROLE {{ .Values.codimd.codimd.database.username }} WITH ENCRYPTED PASSWORD '{{ .Values.codimd.codimd.database.password }}';

    ALTER DATABASE {{ .Values.codimd.codimd.database.databaseName }} OWNER TO {{ .Values.codimd.codimd.database.username }};

    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.codimd.codimd.database.databaseName }} TO {{ .Values.codimd.codimd.database.username }};
