{{- $domains := list "ccadmin" "bs" "cis" "cp" "fsn" "hcp03" "hec" "monsoon3" "neo" "s4" "wbs"}}
{{- if not .Values.global.domain_seeds.skip_hcm_domain -}}
  {{- $domains = append $domains "hcm" }}
{{- end -}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: swift-support-seed
  labels:
    app: {{ tuple .Release .Chart .Values | include "fullname" }}
    chart: "{{ .Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: objectstore
    type: seed
spec:
  requires:
  - swift/swift-seed
  {{- range $domains }}
  - monsoon3/domain-{{ . | lower }}-seed
  {{- end }}

  domains:
    {{- range $domains }}
    - name: {{ . | lower }}
      groups:
      - name: {{ . | upper }}_API_SUPPORT
        role_assignments:
        - project: api_support
          role: objectstore_admin
        {{- if eq . "ccadmin" }}
        - project: api_tools
          role: objectstore_admin
        {{- end }}
        # Inherit admin role within domain
        - domain: {{ . | lower }}
          role: objectstore_admin
          inherited: true
      - name: {{ . | upper }}_COMPUTE_SUPPORT
        role_assignments:
        - project: compute_support
          role: objectstore_admin
        {{- if eq . "ccadmin" }}
        - project: compute_tools
          role: objectstore_admin
        {{- end }}
        # No readonly role to inherit within domain
      - name: {{ . | upper }}_NETWORK_SUPPORT
        role_assignments:
        - project: network_support
          role: objectstore_admin
        {{- if eq . "ccadmin" }}
        - project: network_tools
          role: objectstore_admin
        {{- end }}
        # No readonly role to inherit within domain
      - name: {{ . | upper }}_STORAGE_SUPPORT
        role_assignments:
        - project: storage_support
          role: objectstore_admin
        {{- if eq . "ccadmin" }}
        - project: storage_tools
          role: objectstore_admin
        {{- end }}
        # Inherit admin role within domain
        - domain: {{ . | lower }}
          role: objectstore_admin
          inherited: true
      - name: {{ . | upper }}_SERVICE_DESK
        role_assignments:
        - project: service_desk
          role: objectstore_admin
        # No readonly role to inherit within domain
    {{- end }}
